import { Nav } from "@/components/Nav";
import { Toaster } from "@/components/ui/sonner";
import "@aws-amplify/ui-react/styles.css";
import { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${geistSans.variable} ${geistMono.variable} `}>
        <div className="w-4/6 mx-auto">
          <Nav />
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  );
}
