"use client";
import { Toaster } from "@/components/ui/sonner";
import { AuthProvider } from "@/contexts/AuthContext";
import "@aws-amplify/ui-react/styles.css";
import { Amplify } from "aws-amplify";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import outputs from "../amplify_outputs.json";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
Amplify.configure(outputs);

export default function RootLayout(props: {
  auth: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>
          <div className="w-5/6 mx-auto">
            {props.children}
            {props.auth}
          </div>
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
